### ISSUE TITLE
Images blink and vanish

### ISSUE THREAD

**Issue by bjarkehansen** [talklittle/reddit-is-fun#253] opened 2012-04-26 19:23 UTC
When I click on a direct link to an image, the image is shown for a split second and then disappears. If I double click twice (zoom in, zoom out), I can see the image again. If I close the running tasks and open RIF, it works for a little while. I have One S, which never goes under 100 mb ram. The same issue applies to BaconReader. If I open links in the external browser, they load fine.

**Comment by talklittle** [comment] 2012-04-27 11:44
Thanks for the bug report. I have already made a couple bugfixes in my development branch that affect the browser loading behavior, but not 100% sure if it will fix image vanishing, since I have not reproduced the issue myself.

If it doesn't work then I will be looking at better image handling within the next 2 major versions, anyway.

**Comment by jspidey** [comment] 2012-05-15 04:23
I've got the same issue.  Oddly enough, I'm on an HTC One X.  I found that if I rotate the phone, the image will display again but the double-click works for me too (thanks for the tip).  Seems to be links that open direct to an image.  I've used the menu to open them in the browser to find where they are hosted and it's done this on imgur.com links and deviantart.com links.  Not sure if it's relevant but figured it may help.

**Comment by talklittle** [comment] 2012-05-15 04:43
Thanks for chiming in. I'm still wondering what the cause is. Possibly related to http://code.google.com/p/android/issues/detail?id=20446 ?

**Comment by talklittle** [comment] 2012-05-19 00:05
Version 2.3.2 on Google Play Store reportedly reduces the flickering, but hasn't completely eliminated it yet

**Comment by jspidey** [comment] 2012-06-11 12:22
Yes, I've noticed that after one of the latest updates a majority of the images will sometimes flicker then show properly.  I don't have so many "failed to display" events, if you will.  Nice work!

**Comment by talklittle** [comment] 2012-06-11 12:51
Cool thanks for commenting. I think version 2.3.6 currently on Google Play fixes it most of the time.

Also I discovered it only affects HTC devices running ICS. Not sure whether Sense is the cause.

**Comment by bjarkehansen** [comment] 2012-06-14 10:22
Sorry I didn't comment sooner.

The current version on Google Play still has problems with the images.
The images and pages load fine (99%) but when I scroll, the pages sometimes turn black (I'm using the dark theme if that is relevant). Sometimes it's only part of the page that turns black.

Before scrolling: http://i.imgur.com/RKqYJ.png
After scrolling: http://i.imgur.com/oC7Qr.png
Another example after scrolling: http://i.imgur.com/uhuWT.png

**Comment by talklittle** [comment] 2012-06-14 14:07
Thanks ujusu. I wonder if you can try this download: https://github.com/downloads/talklittle/reddit-is-fun/reddit-is-fun-lite_2.3.6-gh253.apk

, which should eliminate the bug but may leave you with white backgrounds when viewing images. I guess that's an acceptable tradeoff.

**Comment by bjarkehansen** [comment] 2012-06-14 19:38
The apk you linked combines the two issues. The images disappears. And when they show they disappear when I scroll.

**Comment by talklittle** [comment] 2012-06-14 21:58
Crap. ok, thanks. (I'll remove the APK)

**Comment by talklittle** [comment] 2012-06-23 18:17
I'm now pretty confident that the latest version 2.4.2, fixes images.

https://github.com/downloads/talklittle/reddit-is-fun/reddit-is-fun-lite_2.4.2.apk

**Comment by bjarkehansen** [comment] 2012-06-23 19:04
I'm testning it now. Seems promising. The first image didn't work but the next ten did. And very smoothly.

The "changes" list is not in the right order. The latest two changes are switched.

**Comment by bjarkehansen** [comment] 2012-06-23 19:12
Still doesn't work. Sometimes they don't appear at all. Sometimes for a split second. But the workaround is the smoothest yet.

**Comment by talklittle** [comment] 2012-06-23 19:59
Argh. Can't believe it's still not working. I'll have to wait for more feedback from other users. Seems each device behaves differently, even within HTC!

**Comment by talklittle** [comment] 2012-06-24 00:07
I have another update that might work better: https://github.com/downloads/talklittle/reddit-is-fun/reddit-is-fun-lite_2.4.2-nate.apk

**Comment by jspidey** [comment] 2012-06-24 13:57
I just tried the last one you posted. I'm still seeing the issue with the image not loading every now and then. it seems to only be imgur.com pics so far. the oddest example of it, found an album of a Zelda cosplay. It loaded the first two pictures fully, the third image loaded, but the top half was clear but the bottom was pixelated like it didn't fully load. the rest of the pics had not loaded at all. Once I hit the Zoom button, everything was there instantly like it really did load, it just didnt fully render. Thanks for sticking this out with us. Kinda sad that it only seems to be just us two with the issue - there has to be more ppl with the issue...lol

**Comment by talklittle** [comment] 2012-06-24 14:42
Haha, there are definitely other users with HTC devices who have the same issue. I have gotten a bunch of emails, I neglected to direct them to this github issue though.

Thanks a lot for trying it out jspidey and ujusu. I have a feeling this is the best I can do with the "workaround." I think to completely fix it I'll have to just try something completely different like a special image viewer.

**Comment by jspidey** [comment] 2012-06-24 16:29
Again, thanks for trying. glad to see it's not just us. I'm still sticking with this app despite the issue. It just works well for everything else.

**Comment by bjarkehansen** [comment] 2012-06-25 20:32
The latest version you posted has worked for me all day... I will report back in a couple of days.

**Comment by talklittle** [comment] 2012-06-25 21:07
Interesting. Thanks ujusu!

**Comment by jspidey** [comment] 2012-06-26 00:09
I've been using it a bit today and its been working fine. Maybe my inet was wonky at the time. I'll report back in a day or so about how its working.

**Comment by talklittle** [comment] 2012-06-26 00:15
That's awesome. I'll try not to get excited yet.

**Comment by jspidey** [comment] 2012-07-01 14:08
So, it's still occurring for me from time to time. I'm thinking it's something in the timing with receiving all the data for the page. I say this because it occurred only a handful of times the three days after my last post (really, I could count them on one hand), but the past couple days it's happened more frequently. It stinks that I'm still seeing it, but I don't think the app is 100% at fault here.

**Comment by talklittle** [comment] 2012-07-01 14:24
Thanks for the info. I'll try to add more hacks, then.

**Comment by bjarkehansen** [comment] 2012-07-01 14:29
It also works almost perfectly for me.

**Comment by jspidey** [comment] 2012-07-06 17:51
Not sure why, but I'm having no luck with it today.  Nearly every image I try to view I have to zoom in or tip the phone 90deg.

**Comment by talklittle** [comment] 2012-07-06 19:11
damn. thanks for the info. I hope that's not after updating to 2.4.5 which I released a couple hours ago?

**Comment by jspidey** [comment] 2012-07-06 21:26
Just looked, I'm on 2.4.4 still (do see the update in the market though).  I know it's not much help, but I really don't think it can't be _just_ the app if it's been working fine for most of the week then acting up again.  I'll browse around some more with it tonight before upgrading just to see.

**Comment by bjarkehansen** [comment] 2012-07-12 11:04
> 98% of the time it's working 100% of the time. Thank you!

Bugs:
1)
When loading a webpage, the initially displayed part of the page shows fine but when you scroll the new parts are pixelated and when you scroll further the page goes blank.
http://i.imgur.com/ByaSc.png (Notice that 1/5 of the screenshot is white).
Zooming in and out a couple of times usually resolves the issue.

2)
When you click a reddit link that points to an imgur page with an image it loads fine. But sometimes when you click the image to go to the image itself the page is blank. I suppose this is because your hack only works on the page that loads first.

Neither of the bugs are too interruptive so I don't mind them. But I thought you should know.

**Comment by jspidey** [comment] 2012-07-12 15:20
Those are the exact same things that have been occurring to me.  It's been happening 100% lately on every link that goes to just the image as ujusu stated in item #2 of the last post.  I've also noticed that sometimes the image does appear if only for a brief second, then disappears.

**Comment by talklittle** [comment] 2012-07-12 15:38
Thanks guys. I'll put high priority on fixing this using some alternative method other than the zoom hacks I've been trying.

**Comment by jspidey** [comment] 2012-07-16 13:20
Saw something odd happen.  I viewed a thread that linked to an Imgur page with an animated GIF.  Even after the GIF fully loaded, the whole page would flash as the image changed, skipping some frames, but then showing them the next cycle.

**Comment by talklittle** [comment] 2012-07-30 17:44
version 2.5.2 should fix @ujusu problem with the scrolling page. I changed the hardware acceleration settings for those pages specifically.

Not sure about GIFs though. It may be resolved in 2.5.2 too, since I try to load images directly when possible, instead of the imgur page including the frame.

**Comment by talklittle** [comment] 2012-08-08 12:38
Regression in 2.5.3 reintroduced problem with HTC. It'll be fixed in 2.5.4.

**Comment by talklittle** [comment] 2012-08-08 14:02
2.5.3a releasing right now, should fix on HTC again. thanks for your help guys. I'm closing this for now

**Closed as completed by talklittle** 2012-08-08 14:02 UTC
Labels: bug
