### ISSUE TITLE
Dark Theme is White on ICS

### ISSUE THREAD

**Issue by jzelinskie** [talklittle/reddit-is-fun#205] opened 2011-12-16 07:29 UTC
The dark theme is entirely white on ICS unless you are scrolling. In which case, the bar with the "next" button is still white. This is  only on the frontpage/subreddit view. Comment view and all other parts of the UI are correctly colored.

**Comment by talklittle** [comment] 2011-12-16 12:32
Duplicate of #144

Workaround: Works when closing app and launching a fresh instance.

**Closed as completed by talklittle** 2011-12-16 12:32 UTC
Labels: duplicate
