### ISSUE TITLE
Doesn't save comment sorting

### ISSUE THREAD

**Issue by flailking** [talklittle/reddit-is-fun#75] opened 2010-08-04 20:34 UTC
I prefer to sort comments by top, not best. When accessing from droid it always reverts to sort by best. Then when i access the site from PC, my default has changed to best from top. On moto droid, problem occurs on 2.1 and 2.2...other than that...kicks ass

**Comment by talklittle** [comment] 2010-08-04 20:42
thanks I'll fix this.

**Comment by talklittle** [comment] 2010-08-04 20:42
duplicate of #61

**Closed as completed** 2010-08-04 20:43 UTC
Labels: duplicate
