### ISSUE TITLE
"load more comments" not loading more comments

### ISSUE THREAD

**Issue by ghost** [talklittle/reddit-is-fun#258] opened 2012-06-25 18:35 UTC
Using Samsung galaxy 2 epic Sprint, Android 2.3.6, Reddit is Fun Gold Platinum 2.4.1.

Otherwise, l like the new UI & runs very smoothly.

**Comment by talklittle** [comment] 2012-06-25 21:04
Thanks @bluespapa I'll investigate.

**Comment by ghost** [comment] 2012-06-25 21:20
Hi, Andrew,

I'm finding everything is opening now except one, here
http://www.reddit.com/r/sex/comments/vjig8/not_sure_if_this_is_the_right_place_for_this_so/.compactthe
first one that comes up for me. That's right after this comment:

http://www.reddit.com/r/sex/comments/vjig8/not_sure_if_this_is_the_right_place_for_this_so/c551vzm

If I did that right. All others are working.
On Jun 25, 2012 4:04 PM, "Andrew Shu" <
reply@reply.github.com>
wrote:

**Comment by talklittle** [comment] 2012-06-25 21:22
That's very helpful info. Thanks.

**Comment by talklittle** [comment] 2012-06-27 21:09
I've determined that this is kind-of not a bug, just poor UI; if you try clicking on the real website, it also just disappears without loading additional child comments.

To make the UI clearer, I now pop up a short Toast message "no more comments" and remove the "load more comments" from the comments list, in this weird situation. I'm guessing it happens when the child comment was deleted. For some reason, the "load more comments" remains.

(fixed in v2.4.3)

**Closed as completed by talklittle** 2012-06-27 21:09 UTC
Labels: bug, fixed

**Comment by ghost** [comment] 2012-06-28 20:55
I wondered if there were a comment that was deleted. Thanks!
On Jun 27, 2012 4:09 PM, "Andrew Shu" <
reply@reply.github.com>
wrote:
